package com.ftn.sbnz.model.model;

public enum OblikNasilja {
    // FIZICKO - NIVO 1
    UDARANJE_CVRGA,
    GURANJE,
    STIPANJE,
    GADJANJE,
    SAPLITANJE,
    SUTIRANJE,
    PRLJANJE,

    // VERBALNO - NIVO 1
    OMALOVAZAVANJE,
    OGOVARANJE,
    VREDJANJE,
    RUGANJE,
    NAZIVANJE_POGRDNIM_IMENOM,
    PSOVANJE,
    ETIKETIRANJE,

    //SOCIJALNO - NIVO 1
    ODBACIVANJE_IZ_GRUPE,
    ISMEVANJE,
    SIRENJE_GLASINA,

    // SEKSULANO - NIVO 1
    DOBACIVANJE,
    S_PSOVANJE,
    KOMENTARI,
    S_ETIKETIRANJE,
    SEKSUALNA_GESTIKULACIJA,

    // INFORMATICKO - NIVO 1
    UZNEMIRAVAJUCI_POZIVI,
    UZNEMIRAVAJUCE_PORUKE,

    //////////////////////////////
    // FIZICKO - NIVO 2
    SAMARANJE,
    UDARANJE,
    CEPANJE_ODELA,
    GAZENJE,
    PLJUVANJE,
    UNISTAVAJNE_IMOVINE,
    IZMICANJE_STOLICE,
    CUPANJE_ZA_KOSU,

    // VERBALNO - NIVO 2
    UCENJIVANJE,
    PRETNJE,
    NEPRAVEDNO_KAZNJAVANJE,
    ZABRANA_KOMUNIKACIJE,

    // SOCIJALNO - NIVO 2
    SPLETKARENJE,
    IGNORISANJE,
    MANIPULISANJE,
    ISKORISCAVANJE,

    // SEKSUALNO - NIVO 2
    DODIRIVANJE,
    POKAZIVANJE_PORNOGRAFSKOG_MATERIJALA,
    POKAZIVANJE_INTIMNIH_DELOVA_TELA,
    SVLACENJE,

    // INFORMACIONO - NIVO 2
    OGLASAVANJE,
    SNIMANJE_I_SIRENJE_VIDEO_ZAPISA,
    ZLOUPOTREBA_DRUSTVENIH_MREZA,


    //////////////////////////////
    // FIZICKO - NIVO 3
    TUCA,
    DAVLJENJE,
    USKRACIVANJE_HRANE,
    NAPAD_ORUZJEM,
    IZLAGANJE_NISKIM_I_VISOKIM_TEMPERATURAMA,

    // VERBALNO - NIVO 3
    ZASTRASIVANJE,
    UCENJIVANJE_UZ_OZBILJNU_PRETNJU,
    NAVODJENJE_NA_KORISCENJE_PSIHOAKTIVNIH_SUPSTANCI,

    // SOCIJALNO - NIVO 3
    IZOLACIJA,
    MALTRETIRANJE_GRUPE_PREMA_POJEDINCU,
    ORGANIZOVANJE_ZATVORENIH_GRUPA_KOJI_IMA_ZA_POSLEDICU_POVREDJIVANJE_DRUGIH,

    // SEKSUALNO - NIVO 3
    PODVODJENJE,
    SILOVANJE,

    // INFORMACIONO - NIVO 3
    SNIMANJE_I_SIRENJE_VIDEO_ZAPISA_SA_NASILNIM_SCENAMA,
    DECIJA_PORNOGRAFIJA
}
