package rules.com.ftn;

import rules.com.ftn.SanctionForStudent;
import rules.com.ftn.VdpForStudent;
//import function rules.com.ftn.isInLastThreeMonths;

import java.time.LocalDate
import com.ftn.sbnz.model.model.Report
import com.ftn.sbnz.model.model.Vdp
import com.ftn.sbnz.model.model.Sanction
import com.ftn.sbnz.model.model.NivoSklonostiKaNasilju
import com.ftn.sbnz.model.model.NivoNasilja
import com.ftn.sbnz.model.model.HistoryItem;

// 3
////////////////////////////////////////////////////////////////////////////////////////////////////
rule "when: Report for 2nd level violence, then pojacan rad nastavnika"
    lock-on-active true
    when
        $report: Report(
            nivoNasilja == NivoNasilja.DRUGI,
            $student: student,
            $nivo: nivoNasilja,
            $tip: tipNasilja,
            $oblik: oblikNasilja,
            $opis: opis
        )
        Number(intValue == 0) from accumulate (
            $historyItem: HistoryItem()
            from $student.getHistory(),
            count(isInLastThreeMonths($historyItem))
        )
    then
        HistoryItem $item = new HistoryItem($student, $nivo, $tip, $oblik, $opis, Vdp.POJACAN_RAD_NASTAVNIKA, null, LocalDate.now());
        $student.addToHistory($item);

        VdpForStudent $vdpfs = new VdpForStudent();
        $vdpfs.setStudent($student);
        $vdpfs.setVdp(Vdp.POJACAN_RAD_NASTAVNIKA);
        $vdpfs.setHistoryItem($item);

        insert($vdpfs);

        System.out.println("COMPLEX 3: Added report for violence level: " + $report.getNivoNasilja() + "  for student with id: " + $student.getId());
end

rule "when: pojacan rad nastavnika and nivo sklonosti NEMA, then suspension for 3 days"
    no-loop true
    when
        $vdpfs: VdpForStudent(
            $student: student,
            vdp == Vdp.POJACAN_RAD_NASTAVNIKA,
            $student.getNivoSklonosti() == NivoSklonostiKaNasilju.NEMA
        )
    then
        HistoryItem $item = $vdpfs.getHistoryItem();
        $item.setSanction(Sanction.SUSPENSION_3);

        SanctionForStudent $sanctionfs = new SanctionForStudent();
        $sanctionfs.setStudent($student);
        $sanctionfs.setSanction(Sanction.SUSPENSION_3);
        $sanctionfs.setHistoryItem($item);

        insert($sanctionfs);

        System.out.println("Added sanction: " + $sanctionfs.getSanction().getDescription() + "  for student with id: " + $student.getId());
end

rule "when suspension for 3 days and student violence level NEMA, then student violence level SREDNJI"
    no-loop true
    when
        $sanctionfs: SanctionForStudent(
            $student: student,
            sanction == Sanction.SUSPENSION_3,
            $student.getNivoSklonosti() == NivoSklonostiKaNasilju.NEMA
        )
    then
        $student.setNivoSklonosti(NivoSklonostiKaNasilju.SREDNJI);
        System.out.println("Set nivo sklonosti ka nasilju to: " + NivoSklonostiKaNasilju.SREDNJI + "  for student with id: " + $student.getId());
end

// 4
////////////////////////////////////////////////////////////////////////////////////////////////////
rule "when: Report for 2nd level violence and previously reported for 1st level, then pojacan rad pps"
    lock-on-active true
    when
        $report: Report(
            nivoNasilja == NivoNasilja.DRUGI,
            $student: student,
            $nivo: nivoNasilja,
            $tip: tipNasilja,
            $oblik: oblikNasilja,
            $opis: opis
        )
        Number(intValue >= 1) from accumulate (
            $historyItem: HistoryItem(
                nivoNasilja == NivoNasilja.PRVI
            ) from $student.getHistory(),
            count(isInLastThreeMonths($historyItem))
        )
        Number(intValue == 0) from accumulate (
            $historyItem: HistoryItem(
                nivoNasilja == NivoNasilja.DRUGI
            ) from $student.getHistory(),
            count(isInLastThreeMonths($historyItem))
        )
    then
        HistoryItem $item = new HistoryItem($student, $nivo, $tip, $oblik, $opis, Vdp.POJACAN_RAD_PPS, null, LocalDate.now());
        $student.addToHistory($item);

        VdpForStudent $vdpfs = new VdpForStudent();
        $vdpfs.setStudent($student);
        $vdpfs.setVdp(Vdp.POJACAN_RAD_PPS);
        $vdpfs.setHistoryItem($item);

        insert($vdpfs);

        System.out.println("COMPLEX 4: Added report for violence level: " + $report.getNivoNasilja() + "  for student with id: " + $student.getId());
end

rule "when: pojacan rad pps and nivo sklonosti LAKSI, then suspension for 3 days"
    no-loop true
    when
        $vdpfs: VdpForStudent(
            $student: student,
            vdp == Vdp.POJACAN_RAD_PPS,
            $student.getNivoSklonosti() == NivoSklonostiKaNasilju.LAKSI ||
            $student.getNivoSklonosti() == NivoSklonostiKaNasilju.SREDNJI
        )
    then
        HistoryItem $item = $vdpfs.getHistoryItem();
        $item.setSanction(Sanction.SUSPENSION_3);

        SanctionForStudent $sanctionfs = new SanctionForStudent();
        $sanctionfs.setStudent($student);
        $sanctionfs.setSanction(Sanction.SUSPENSION_3);
        $sanctionfs.setHistoryItem($item);

        insert($sanctionfs);

        System.out.println("Added sanction: " + $sanctionfs.getSanction().getDescription() + "  for student with id: " + $student.getId());
end

rule "when suspension for 3 days and nivo sklonosti ka nasilju LAKSI, then set nivo sklonosti na SREDNJI"
    no-loop true
    when
        $sanctionfs: SanctionForStudent(
            $student: student,
            sanction == Sanction.SUSPENSION_3,
            $student.getNivoSklonosti() == NivoSklonostiKaNasilju.LAKSI
        )
    then
        $student.setNivoSklonosti(NivoSklonostiKaNasilju.SREDNJI);
        System.out.println("Set nivo sklonosti ka nasilju to: " + NivoSklonostiKaNasilju.SREDNJI + "  for student with id: " + $student.getId());
end

// 5
////////////////////////////////////////////////////////////////////////////////////////////////////
rule "when: Report for 2nd level violence and previously reported for 2nd level, then pojacan rad pps i sc"
    lock-on-active true
    when
        $report: Report(
            nivoNasilja == NivoNasilja.DRUGI,
            $student: student,
            $nivo: nivoNasilja,
            $tip: tipNasilja,
            $oblik: oblikNasilja,
            $opis: opis
        )
        Number(intValue >= 1) from accumulate (
            $historyItem: HistoryItem(
                nivoNasilja == NivoNasilja.DRUGI
            ) from $student.getHistory(),
            count(isInLastThreeMonths($historyItem))
        )
    then
        HistoryItem $item = new HistoryItem(
                $student,
                $nivo,
                $tip,
                $oblik,
                $opis,
                Vdp.POJACAN_RAD_SS,
                null,
                LocalDate.now()
        );
        $student.addToHistory($item);

        VdpForStudent $vdpfs = new VdpForStudent();
        $vdpfs.setStudent($student);
        $vdpfs.setVdp(Vdp.POJACAN_RAD_SS);
        $vdpfs.setHistoryItem($item);

        insert($vdpfs);

        System.out.println("COMPLEX 5: Added report for violence level: " + $report.getNivoNasilja() + "  for student with id: " + $student.getId());
end

rule "when: pojacan rad pps i sc i nivo sklonosti SREDNJI, then suspension for 7 days"
    no-loop true
    when
        $vdpfs: VdpForStudent(
            $student: student,
            vdp == Vdp.POJACAN_RAD_SS
        )
    then
        HistoryItem $item = $vdpfs.getHistoryItem();
        $item.setSanction(Sanction.SUSPENSION_7);

        SanctionForStudent $sanctionfs = new SanctionForStudent();
        $sanctionfs.setStudent($student);
        $sanctionfs.setSanction(Sanction.SUSPENSION_7);
        $sanctionfs.setHistoryItem($item);

        insert($sanctionfs);

        System.out.println("Added sanction: " + $sanctionfs.getSanction().getDescription() + "  for student with id: " + $student.getId());
end

rule "when: suspension for 7 days and nivo sklonosti SREDNJI, then set nivo sklonosti na TEZI"
    when
        $sanctionfs: SanctionForStudent(
            $student: student,
            sanction == Sanction.SUSPENSION_7
        )
    then
        $student.setNivoSklonosti(NivoSklonostiKaNasilju.TEZI);
        System.out.println("Set nivo sklonosti ka nasilju to: " + NivoSklonostiKaNasilju.TEZI + "  for student with id: " + $student.getId());
end





















