package rules.com.ftn;
import java.time.LocalDate
import com.ftn.sbnz.model.model.HistoryItem;

function boolean isInLastThreeMonths(HistoryItem $item) {
    LocalDate $endDate = LocalDate.now();
    LocalDate $startDate = $endDate.minusMonths(3);
    LocalDate $reportDate = $item.getReportDate();

    System.out.println("MY CUSTOM FUNCTION FOR ITEM: " + $item.getId());

    return !$reportDate.isBefore($startDate) && !$reportDate.isAfter($endDate);
}
