package rules.com.ftn;
import java.time.LocalDate
import com.ftn.sbnz.model.model.HistoryItem;

//    System.out.println("isInLastThreeMonths called for history item: " + $item.getId());
function boolean isInLastThreeMonths(HistoryItem $item) {

    LocalDate $endDate = LocalDate.now();
    LocalDate $startDate = $endDate.minusMonths(3);
    LocalDate $reportDate = $item.getReportDate();

    return !$reportDate.isBefore($startDate) && !$reportDate.isAfter($endDate);
}
